[package]
name = "ublox-cellular-rs"
version = "0.4.0"
authors = ["Mathias Koch <mk@blackbird.online>"]
description = "Driver crate for u-blox cellular devices, implementation follows 'UBX-13002752 - R65'"
readme = "../README.md"
keywords = ["arm", "cortex-m", "ublox", "cellular", "embedded-hal-driver"]
categories = ["embedded", "no-std"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/BlackbirdHQ/ublox-cellular-rs"
edition = "2021"

[lib]
name = "ublox_cellular"
doctest = false

[dependencies]
atat = { version = "0.21.0", features = ["derive", "bytes"] }
heapless = { version = "^0.8", features = ["serde"] }
nb = "^1"
serde = { version = "^1", default-features = false, features = ["derive"] }
#ublox-sockets = { version = "0.5", optional = true }
ublox-sockets = { git = "https://github.com/BlackbirdHQ/ublox-sockets", branch = "feature/async-borrowed-sockets", optional = true }
embassy-time = "0.3"
embassy-sync = "0.5"

no-std-net = { version = "^0.6", features = ["serde"] }

log = { version = "^0.4", default-features = false, optional = true }
defmt = { version = "^0.3", optional = true }

futures-util = { version = "0.3.29", default-features = false }

embassy-futures = { version = "0.1" }

embedded-hal = "1.0.0"
embedded-nal = "0.8"
embedded-nal-async = { version = "0.7" }

embassy-at-cmux = { path = "../embassy/embassy-at-cmux", optional = true }
embassy-net-ppp = { version = "0.1", optional = true }
embassy-net = { version = "0.4", features = [
    "proto-ipv4",
    "medium-ip",
], optional = true }
embassy-embedded-hal = { version = "0.1", optional = true }

embedded-io-async = "0.6"

[features]
default = ["socket-udp", "socket-tcp", "ppp"]

internal-network-stack = ["dep:ublox-sockets"]
ppp = ["dep:embassy-at-cmux", "dep:embassy-net-ppp", "dep:embassy-net"]

automatic-apn = []
upsd-context-activation = []

socket-tcp = ["ublox-sockets?/socket-tcp", "embassy-net?/tcp"]
socket-udp = ["ublox-sockets?/socket-udp", "embassy-net?/udp"]

defmt = [
    "dep:defmt",
    "atat/defmt",
    "heapless/defmt-03",
    "embassy-time/defmt",
    "embassy-sync/defmt",
    "embassy-futures/defmt",
    "ublox-sockets?/defmt",
    "embassy-net-ppp?/defmt",
    "embassy-net?/defmt",
    "embassy-at-cmux?/defmt",
]
log = ["dep:log", "ublox-sockets?/log", "atat/log"]

lara-r2 = []
lara-r6 = []
leon-g1 = []
lisa-u2 = []
mpci-l2 = []
sara-g3 = []
sara-g4 = []
sara-r5 = ["upsd-context-activation"]
sara-u1 = []
sara-u2 = ["upsd-context-activation"]
toby-l2 = []
toby-r2 = []
toby-l4 = []

[workspace]
members = []
default-members = ["."]
exclude = ["examples"]

[patch.crates-io]
#ublox-sockets = { git = "https://github.com/BlackbirdHQ/ublox-sockets", branch = "feature/async-borrowed-sockets" }
no-std-net = { git = "https://github.com/rushmorem/no-std-net", branch = "issue-15" }
#ublox-sockets = { path = "../ublox-sockets" }
# atat = { git = "https://github.com/BlackbirdHQ/atat", branch = "master" }
embassy-time = { git = "https://github.com/embassy-rs/embassy", branch = "main" }
embassy-sync = { git = "https://github.com/embassy-rs/embassy", branch = "main" }
embassy-futures = { git = "https://github.com/embassy-rs/embassy", branch = "main" }
embassy-net-ppp = { git = "https://github.com/embassy-rs/embassy", branch = "main" }
embassy-net = { git = "https://github.com/embassy-rs/embassy", branch = "main" }

#embassy-time = { path = "../embassy/embassy-time" }
#embassy-sync = { path = "../embassy/embassy-sync" }
#embassy-futures = { path = "../embassy/embassy-futures" }
atat = { path = "../atat/atat" }
